import { Geist, Geist_Mono } from "next/font/google";
import { redirect } from "next/navigation";
import { auth } from "../auth";
import TopBar from "../components/TopBar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Task Manager",
  description: "Generated by github.com/muhamash",
};

export default async function RootLayout ( { children } )
{
  const session = await auth();
  console.log( session );
  if ( session?.error === "RefreshAccessTokenError" ||  session?.error === "SessionExpired" )
  {
    redirect( "/login" );
  }
  
  return (
    <html lang="en">
      <body
        className={ `${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white` }
      >
        <TopBar session={ session } />
          { children }
      </body>
    </html>
  );
}